version: '3.8'

services:
  yt-dlp-api:
    build: .
    container_name: yt-dlp-api
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount cookies directory for authentication (your YouTube cookies) - WRITABLE
      - ./yt_dlp/cookies:/app/cookies
      # Optional: Mount Chrome profile for direct browser cookie access
      - ~/.config/google-chrome:/root/.config/google-chrome:ro
      - ~/.cache/google-chrome:/root/.cache/google-chrome:ro
    
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Docker cleanup service - runs daily at 2 AM
  docker-cleanup:
    image: alpine:latest
    container_name: yt-dlp-cleanup
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=UTC
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        echo '0 2 * * * docker system prune --volumes -f' | crontab - &&
        echo '0 3 * * 0 docker image prune -a -f' | crontab - &&
        crond -f -l 2
      "
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1' 